// <auto-generated />
using System;
using ChallengeCollector;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChallengeCollector.Migrations
{
    [DbContext(typeof(ChallengeCollectorDbContext))]
    partial class ChallengeCollectorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChallengeCollector.Models.ChallengeResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Passphrase")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("passphrase");

                    b.Property<byte[]>("ResultFile")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("result_file");

                    b.Property<long>("ResultFileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("result_file_size");

                    b.Property<byte[]>("TestFile")
                        .HasColumnType("bytea")
                        .HasColumnName("test_file");

                    b.Property<long?>("TestFileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("test_file_size");

                    b.Property<string>("UniqueHandle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unique_handle");

                    b.HasKey("Id")
                        .HasName("pk_challenge_response");

                    b.HasIndex("UniqueHandle")
                        .HasDatabaseName("ix_challenge_response_unique_handle");

                    b.ToTable("challenge_response", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
